version: '3'

services:
  postgres:
    image: postgres:9.4
    container_name: assessment_engine_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./startup_scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    networks:
      - assessment_engine_network
    logging:
      driver: json-file
      options:
        max-size: "3m"
        max-file: "1"

networks:
  assessment_engine_network:
    name: assessment_engine_network
